apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qsy344lyj-nodejs
  janus-idp.io/tekton: qsy344lyj-nodejs
  backstage.io/kubernetes-id: qsy344lyj-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qsy344lyj-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
